const data = {
  keys: [
    {
      id: "7",
      value: "7",
      label: "7",
      class: "col-3 p-1",
      classBtn: "mx-auto",
    },
    {
      id: "8",
      value: "8",
      label: "8",
      class: "col-3 p-1",
      classBtn: "mx-auto",
    },
    {
      id: "9",
      value: "9",
      label: "9",
      class: "col-3 p-1",
      classBtn: "mx-auto",
    },
    {
      id: "10",
      value: "del",
      label: "DEL",
      class: "col-3 p-1",
      classBtn: "mx-auto",
    },
    {
      id: "4",
      value: "4",
      label: "4",
      class: "col-3 p-1",
      classBtn: "mx-auto",
    },
    {
      id: "5",
      value: "5",
      label: "5",
      class: "col-3 p-1",
      classBtn: "mx-auto",
    },
    {
      id: "6",
      value: "6",
      label: "6",
      class: "col-3 p-1",
      classBtn: "mx-auto",
    },
    {
      id: "11",
      value: "plus",
      label: "+",
      class: "col-3 p-1",
      classBtn: "mx-auto",
    },

    {
      id: "1",
      value: "1",
      label: "1",
      class: "col-3 p-1",
      classBtn: "mx-auto",
    },
    {
      id: "2",
      value: "2",
      label: "2",
      class: "col-3 p-1",
      classBtn: "mx-auto",
    },
    {
      id: "3",
      value: "3",
      label: "3",
      class: "col-3 p-1",
      classBtn: "mx-auto",
    },
    {
      id: "12",
      value: "minus",
      label: "-",
      class: "col-3 p-1",
      classBtn: "mx-auto",
    },
    {
      id: "15",
      value: "dot",
      label: ".",
      class: "col-3 p-1",
      classBtn: "mx-auto",
    },
    {
      id: "0",
      value: "0",
      label: "0",
      class: "col-3 p-1",
      classBtn: "mx-auto",
    },
    {
      id: "14",
      value: "divide",
      label: "/",
      class: "col-3 p-1",
      classBtn: "mx-auto",
    },
    {
      id: "13",
      value: "multiply",
      label: "x",
      class: "col-3 p-1",
      classBtn: "mx-auto",
    },

    {
      id: "16",
      value: "reset",
      label: "RESET",
      class: "col-6 p-1",
      classBtn: "px-4",
    },
    {
      id: "17",
      value: "=",
      label: "=",
      class: "col-6 p-1",
      classBtn: "px-5",
    },
  ],
};
export default data;
